version: '3.8'

services:
  # Frontend Production
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - crm-network

  # Backend Production
  backend:
    # Thay thế bằng production backend image của bạn
    image: your-backend-image:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://crm_user:crm_password@database:3306/crm_db
    depends_on:
      - database
    networks:
      - crm-network

  # Database Production
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mysql_prod_data:
